In [124]:
import seaborn as sns   #读取数据
import pandas as pd
%matplotlib  inline
y = pd.read_csv('./附件1-区域15分钟负荷数据.csv')
indu = pd.read_csv('./附件2-行业日负荷数据.csv')
tianqi = pd.read_csv('./附件3-气象数据.csv')
tianqi = tianqi.drop([0],axis=0)
tianqi

              日期     天气状况 最高温度 最低温度    白天风力风向    夜晚风力风向
1      2018年1月1日    多云/多云  22℃  12℃  无持续风向<3级  无持续风向<3级
2      2018年1月2日    多云/多云  22℃  15℃  无持续风向<3级  无持续风向<3级
3      2018年1月3日     多云/阴  23℃  15℃  无持续风向<3级  无持续风向<3级
4      2018年1月4日    多云/小雨  21℃  16℃  无持续风向<3级  无持续风向<3级
5      2018年1月5日     阴/小雨  19℃  13℃  无持续风向<3级  无持续风向<3级
...          ...      ...  ...  ...       ...       ...
1340  2021年8月27日  雷阵雨/雷阵雨  35℃  26℃    北风1-2级    北风1-2级
1341  2021年8月28日   雷阵雨/多云  33℃  26℃    北风1-2级    北风1-2级
1342  2021年8月29日  雷阵雨/雷阵雨  32℃  25℃    北风1-2级    北风1-2级
1343  2021年8月30日    阵雨/阵雨  34℃  26℃    北风1-2级    北风1-2级
1344  2021年8月31日   雷阵雨/阵雨  32℃  26℃    北风1-2级    北风1-2级

[1344 rows x 6 columns]

In [125]:
#del tianqi['Unnamed: 6']  #删除Unnamed：6

In [126]:
tianqi['最高温度'] = tianqi['最高温度'].map(lambda d: d.replace('℃','')).astype(int)  #使用空格替换摄氏度
tianqi['最低温度'] = tianqi['最低温度'].map(lambda d: d.replace('℃','')).astype(int)

In [127]:
series = tianqi.join(tianqi['天气状况'].str.split('/',expand=True))  #以/切割天气状况并且分配给天气1与天气2
tianqi['天气1'] = series[0]
tianqi['天气2'] = series[1]
tianqi.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1344 entries, 1 to 1344
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   日期      1344 non-null   object
 1   天气状况    1344 non-null   object
 2   最高温度    1344 non-null   int32
 3   最低温度    1344 non-null   int32
 4   白天风力风向  1344 non-null   object
 5   夜晚风力风向  1344 non-null   object
 6   天气1     1344 non-null   object
 7   天气2     1344 non-null   object
dtypes: int32(2), object(6)
memory usage: 116.3+ KB

In [128]:
tianqi['白天风力风向'].unique()  #去重

array(['无持续风向<3级', '北风4～5级', '微风<3级', '北风3', '东北风3～4级', '北风3～4级',
       '南风3～4级', '南风4～5级', '东北偏东风2', '无持续风向微风', '无持续风向1-2级', '东风3-4级',
       '东南风4-5级', '东风3～4级', '东北风3-4级', '东风8-9级', '东南风3-4级', '北风3-4级',
       '北风4-5级', '南风3-4级', '南风1-2级', '东南风1-2级', '西南风3-4级', '东风1-2级',
       '北风1-2级', '东北风1-2级', '西南风1-2级'], dtype=object)

In [129]:
tianqi['夜晚风力风向'].unique()

array(['无持续风向<3级', '北风4～5级', '北风3～4级', '微风<3级', '北风3', '东北偏东风2',
       '无持续风向微风', '无持续风向1-2级', '东风3-4级', '东南风4-5级', '东南风3～4级', '东北风3-4级',
       '东风8-9级', '东南风3-4级', '北风3-4级', '北风4-5级', '南风3-4级', '南风1-2级',
       '东南风1-2级', '西南风3-4级', '东风1-2级', '北风1-2级', '东北风1-2级', '西南风1-2级'],
      dtype=object)

In [130]:
dic = { '无持续风向微风':0, 
        '无持续风向1-2级':1,        
        '东南风1-2级':1,
        '南风1-2级':1,
        '东风1-2级':1,
        '北风1-2级':1,
        '东北风1-2级':1,
        '西南风1-2级':1,
        '东北偏东风2':2, 
        '微风<3级':3, 
        '无持续风向<3级':3,
        '北风3':4,
        '东北风3～4级':5, 
        '东南风3-4级':5,
        '东南风3～4级':5,
        '东风3-4级':5,
        '北风3～4级':5,
        '南风3～4级':5, 
        '南风3-4级':5, 
        '东风3～4级':5, 
        '西南风3-4级':5,
        '东北风3-4级':5, 
        '北风3-4级':5,
        '北风4-5级':6, 
        '北风4～5级':6,
        '南风4～5级':6,
        '东南风4-5级':6, 
        '东风8-9级':7,}  #使用字典映射
tianqi['白天风力风向'] = tianqi['白天风力风向'].map(dic)
tianqi['夜晚风力风向'] = tianqi['夜晚风力风向'].map(dic)

In [131]:
tianqi

              日期     天气状况  最高温度  最低温度  白天风力风向  夜晚风力风向  天气1  天气2
1      2018年1月1日    多云/多云    22    12       3       3   多云   多云
2      2018年1月2日    多云/多云    22    15       3       3   多云   多云
3      2018年1月3日     多云/阴    23    15       3       3   多云    阴
4      2018年1月4日    多云/小雨    21    16       3       3   多云   小雨
5      2018年1月5日     阴/小雨    19    13       3       3    阴   小雨
...          ...      ...   ...   ...     ...     ...  ...  ...
1340  2021年8月27日  雷阵雨/雷阵雨    35    26       1       1  雷阵雨  雷阵雨
1341  2021年8月28日   雷阵雨/多云    33    26       1       1  雷阵雨   多云
1342  2021年8月29日  雷阵雨/雷阵雨    32    25       1       1  雷阵雨  雷阵雨
1343  2021年8月30日    阵雨/阵雨    34    26       1       1   阵雨   阵雨
1344  2021年8月31日   雷阵雨/阵雨    32    26       1       1  雷阵雨   阵雨

[1344 rows x 8 columns]

In [132]:
tianqi['天气1'].unique()  #去重

array(['多云', '阴', '小雨-中雨', '大雨', '中雨', '小雨', '晴', '雷阵雨', '雾', '阵雨',
       '中雨-大雨', '晴间多云', '暴雨', '小到中雨', '中到大雨', '大到暴雨'], dtype=object)

In [133]:
tianqi['天气2'].unique()

array(['多云', '阴', '小雨', '中雨-大雨', '中雨', '小雨-中雨', '晴', '局部多云', '阵雨', '雾',
       '雷阵雨', '大雨', '暴雨', '中到大雨', '小到中雨', '大到暴雨'], dtype=object)

In [134]:
dic1 = { '晴':0, 
         '晴间多云':1,
         '局部多云':2,
         '多云':3,
         '雾':4,
         '阴':5, 
         '阵雨':6,
         '雷阵雨':7,
         '小雨':8,
         '小到中雨':9,
         '小雨-中雨':10, 
         '中雨':11,
         '中雨-大雨':12,
         '大雨':13,
         '大到暴雨':14,
         '暴雨':15
       }
tianqi['天气1'] = tianqi['天气1'].map(dic1)  #使用去重后数据映射
tianqi['天气2'] = tianqi['天气2'].map(dic1)
del tianqi['天气状况']

In [135]:
y = y.rename(columns={'数据时间':'日期1'})  #更改列名称
y['日期'] = y['日期1'].apply(lambda x: x.split(' ')[0])  #使用split分隔日期，把年月日赋值给日期
tianqi.loc[:, '日期'] = pd.to_datetime(tianqi.loc[:, '日期'], format='%Y年%m月%d日', errors='coerce')  #将日期规格化
y.loc[:, '日期'] = pd.to_datetime(y.loc[:, '日期'], format='%Y/%m/%d', errors='coerce') #将日期规格化
train = y.merge(tianqi,on='日期',how='left')  #将y表与tianqi表合并
del train['日期']  #删除日期列

In [136]:
train.to_csv("泰迪杯数据01.csv",index=False,encoding='utf_8_sig')  #将数据写入

In [137]:
train

                       日期1    总有功功率（kw）  最高温度  最低温度  白天风力风向  夜晚风力风向  天气1  天气2
0        2018/1/1 00:00:00  244033.7682    22    12       3       3  3.0  3.0
1        2018/1/1 00:15:00  232720.6402    22    12       3       3  3.0  3.0
2        2018/1/1 00:30:00  231685.6891    22    12       3       3  3.0  3.0
3        2018/1/1 00:45:00  227581.3317    22    12       3       3  3.0  3.0
4        2018/1/1 01:00:00  233482.4269    22    12       3       3  3.0  3.0
...                    ...          ...   ...   ...     ...     ...  ...  ...
128631  2021/8/31 22:45:00  202409.1270    32    26       1       1  7.0  6.0
128632  2021/8/31 23:00:00  218576.4635    32    26       1       1  7.0  6.0
128633  2021/8/31 23:15:00  200112.5091    32    26       1       1  7.0  6.0
128634  2021/8/31 23:30:00  199865.5937    32    26       1       1  7.0  6.0
128635  2021/8/31 23:45:00  198483.5592    32    26       1       1  7.0  6.0

[128636 rows x 8 columns]

In [138]:
indu_da = indu.iloc[0:973,:]
indu_da = indu_da.rename(columns={'数据时间':'日期1'})  #更改列名称
indu_da['日期'] = indu_da['日期1'].apply(lambda x: x.split(' ')[0])  #使用split分隔日期，把年月日赋值给日期
indu_da.loc[:, '日期'] = pd.to_datetime(indu_da.loc[:, '日期'], format='%Y/%m/%d', errors='coerce') #将日期规格化
train = indu_da.merge(tianqi,on='日期',how='left')
del train['日期']  #删除日期列

In [139]:
train.to_csv("泰迪杯数据01_大工业.csv",index=False,encoding='utf_8_sig')  #将数据写入

In [140]:
train

,行业类型,日期1,有功功率最大值（kw）,有功功率最小值（kw）,最高温度,最低温度,白天风力风向,夜晚风力风向,天气1,天气2
0,大工业用电,2019-01-01,117888.3300,51526.5690,12,7,1,1,5.0,5.0
1,大工业用电,2019-01-02,126843.7914,63638.4294,11,6,1,1,8.0,8.0
2,大工业用电,2019-01-03,130286.1294,102048.2754,15,9,1,1,3.0,8.0
3,大工业用电,2019-01-04,133018.6344,104466.0762,17,12,1,1,5.0,8.0
4,大工业用电,2019-01-05,133504.4784,99507.3528,17,12,1,1,5.0,8.0
...,...,...,...,...,...,...,...,...,...,...
973,大工业用电,2021-08-27,102950.5320,77916.3834,35,26,1,1,7.0,7.0
974,大工业用电,2021-08-28,107493.4824,82662.1020,33,26,1,1,7.0,3.0
975,大工业用电,2021-08-29,98528.9820,74703.2514,32,25,1,1,7.0,7.0
976,大工业用电,2021-08-30,106633.8348,79252.9464,34,26,1,1,6.0,6.0
977,大工业用电,2021-08-31,101834.8440,74755.6662,32,26,1,1,7.0,6.0

In [141]:
indu_oupu = indu.iloc[973:1664,:]
indu_oupu = indu_oupu.rename(columns={'数据时间':'日期1'})  #更改列名称
indu_oupu['日期'] = indu_oupu['日期1'].apply(lambda x: x.split(' ')[0])  #使用split分隔日期，把年月日赋值给日期
indu_oupu.loc[:, '日期'] = pd.to_datetime(indu_oupu.loc[:, '日期'], format='%Y/%m/%d', errors='coerce') #将日期规格化
train = indu_oupu.merge(tianqi,on='日期',how='left')
del train['日期']  #删除日期列

In [142]:
train.to_csv("泰迪杯数据01_非普工业.csv",index=False,encoding='utf_8_sig')  #将数据写入

In [143]:
train

,行业类型,日期1,有功功率最大值（kw）,有功功率最小值（kw）,最高温度,最低温度,白天风力风向,夜晚风力风向,天气1,天气2
0,非普工业,2019-10-10,2621.3316,892.5384,32,25,1,1,3.0,3.0
1,非普工业,2019-10-11,2669.0172,978.3816,33,25,1,1,0.0,0.0
2,非普工业,2019-10-12,2632.9704,1020.0588,33,24,1,1,3.0,7.0
3,非普工业,2019-10-13,1810.2156,965.6964,31,23,1,1,7.0,7.0
4,非普工业,2019-10-14,2522.4576,943.8792,29,23,1,1,3.0,3.0
...,...,...,...,...,...,...,...,...,...,...
691,非普工业,2021-08-27,3207.7014,1416.9294,35,26,1,1,7.0,7.0
692,非普工业,2021-08-28,2418.1716,1291.5816,33,26,1,1,7.0,3.0
693,非普工业,2021-08-29,2486.0946,1420.2804,32,25,1,1,7.0,7.0
694,非普工业,2021-08-30,3316.1904,1434.9684,34,26,1,1,6.0,6.0
695,非普工业,2021-08-31,3223.6920,1401.9822,32,26,1,1,7.0,6.0

In [144]:
indu_pu = indu.iloc[1664:2637,:]
indu_pu = indu_pu.rename(columns={'数据时间':'日期1'})  #更改列名称
indu_pu['日期'] = indu_pu['日期1'].apply(lambda x: x.split(' ')[0])  #使用split分隔日期，把年月日赋值给日期
indu_pu.loc[:, '日期'] = pd.to_datetime(indu_pu.loc[:, '日期'], format='%Y/%m/%d', errors='coerce') #将日期规格化
train = indu_pu.merge(tianqi,on='日期',how='left')
del train['日期']  #删除日期列

In [145]:
train.to_csv("泰迪杯数据01_普通工业.csv",index=False,encoding='utf_8_sig')  #将数据写入

In [146]:
train

,行业类型,日期1,有功功率最大值（kw）,有功功率最小值（kw）,最高温度,最低温度,白天风力风向,夜晚风力风向,天气1,天气2
0,普通工业,2019-01-01,6179.9364,4093.0467,12,7,1,1,5.0,5.0
1,普通工业,2019-01-02,10711.9704,3971.5308,11,6,1,1,8.0,8.0
2,普通工业,2019-01-03,10079.0262,4033.8369,15,9,1,1,3.0,8.0
3,普通工业,2019-01-04,9713.3055,4145.8497,17,12,1,1,5.0,8.0
4,普通工业,2019-01-05,6958.3842,3965.1792,17,12,1,1,5.0,8.0
...,...,...,...,...,...,...,...,...,...,...
973,普通工业,2021-08-27,10332.7482,2867.6274,35,26,1,1,7.0,7.0
974,普通工业,2021-08-28,6337.3656,3288.4884,33,26,1,1,7.0,3.0
975,普通工业,2021-08-29,6509.8032,3192.6312,32,25,1,1,7.0,7.0
976,普通工业,2021-08-30,10606.9374,3287.0472,34,26,1,1,6.0,6.0
977,普通工业,2021-08-31,10329.5676,3732.4056,32,26,1,1,7.0,6.0

In [147]:
indu_pu = indu.iloc[2637:3610,:]
indu_pu

     行业类型        数据时间  有功功率最大值（kw）  有功功率最小值（kw）
2637   商业  2019-01-01   64027.8582   23758.7970
2638   商业  2019-01-02   75467.2143   20231.6265
2639   商业  2019-01-03  132776.9442   20443.6182
2640   商业  2019-01-04   97731.1308   19858.1592
2641   商业  2019-01-05  132883.1868   19766.6994
...   ...         ...          ...          ...
3605   商业  2021-08-27  104728.8762   19815.7638
3606   商业  2021-08-28   93855.1368   20820.2490
3607   商业  2021-08-29   84127.1658   21679.5828
3608   商业  2021-08-30  102851.2758   21036.5868
3609   商业  2021-08-31   96396.2568   21291.3042

[973 rows x 4 columns]

In [148]:
indu_sh = indu.iloc[2637:3610,:]
indu_sh = indu_sh.rename(columns={'数据时间':'日期1'})  #更改列名称
indu_sh['日期'] = indu_sh['日期1'].apply(lambda x: x.split(' ')[0])  #使用split分隔日期，把年月日赋值给日期
indu_sh.loc[:, '日期'] = pd.to_datetime(indu_sh.loc[:, '日期'], format='%Y/%m/%d', errors='coerce') #将日期规格化
train = indu_sh.merge(tianqi,on='日期',how='left')
del train['日期']  #删除日期列

In [149]:
train.to_csv("泰迪杯数据01_商业.csv",index=False,encoding='utf_8_sig')  #将数据写入

In [150]:
train

,行业类型,日期1,有功功率最大值（kw）,有功功率最小值（kw）,最高温度,最低温度,白天风力风向,夜晚风力风向,天气1,天气2
0,商业,2019-01-01,64027.8582,23758.7970,12,7,1,1,5.0,5.0
1,商业,2019-01-02,75467.2143,20231.6265,11,6,1,1,8.0,8.0
2,商业,2019-01-03,132776.9442,20443.6182,15,9,1,1,3.0,8.0
3,商业,2019-01-04,97731.1308,19858.1592,17,12,1,1,5.0,8.0
4,商业,2019-01-05,132883.1868,19766.6994,17,12,1,1,5.0,8.0
...,...,...,...,...,...,...,...,...,...,...
973,商业,2021-08-27,104728.8762,19815.7638,35,26,1,1,7.0,7.0
974,商业,2021-08-28,93855.1368,20820.2490,33,26,1,1,7.0,3.0
975,商业,2021-08-29,84127.1658,21679.5828,32,25,1,1,7.0,7.0
976,商业,2021-08-30,102851.2758,21036.5868,34,26,1,1,6.0,6.0
977,商业,2021-08-31,96396.2568,21291.3042,32,26,1,1,7.0,6.0